scope: "charmed-postgresql"
namespace: "/postgresql-common/"
name: postgresql

raft:
  data_dir: /var/snap/charmed-postgresql/common/raft
  self_addr: '127.0.0.1:2222'

restapi:
  listen: 127.0.0.1:8008
  connect_address: 127.0.0.1:8008

bootstrap:
  initdb:
    - locale: C
    - encoding: UTF8
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    check_timeline: true
    postgresql:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      remove_data_directory_on_diverged_timelines: true
      use_slots: true
      pg_hba:
        - local   all             all                                     peer
        - host    all             all             127.0.0.1/32            md5
        - host    all             all             ::1/128                 md5
        - local   replication     all                                     peer
        - host    replication     all             127.0.0.1/32            md5
        - host    replication     all             ::1/128                 md5
postgresql:
  listen: "*:5432"
  connect_address: 127.0.0.1:5432
  data_dir: /var/snap/charmed-postgresql/common/postgresql
  bin_dir: /snap/charmed-postgresql/current/usr/lib/postgresql/14/bin
  config_dir: /var/snap/charmed-postgresql/current/postgresql
  pgpass: "/var/snap/charmed-postgresql/current/postgresql/\
      data/14-postgresql.pgpass"
  authentication:
    replication:
      username: "replicator"
      password: "rep-pass"
    superuser:
      username: "postgres"
      password: "pg-pass"
  parameters:
    unix_socket_directories: /tmp
