name: charmed-postgresql # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '14.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: PostgreSQL in a snap.
description: |
  PostgreSQL is a free and open-source relational database management
  system emphasizing extensibility and SQL compliance.  This package
  includes patroni for managing your PostgreSQL systems.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

system-usernames:
  snap_daemon: shared

plugs:
  shared-memory:
    private: true

package-repositories:
  - type: apt
    ppa: data-platform/patroni
  - type: apt
    ppa: data-platform/pgbackrest
  - type: apt
    ppa: data-platform/pgbouncer
  - type: apt
    ppa: data-platform/postgres-exporter
  - type: apt
    ppa: data-platform/pgbouncer-exporter

layout:
  /usr/lib/python3/dist-packages:
    bind: $SNAP/usr/lib/python3/dist-packages
  /etc/perl:
    bind: $SNAP/etc/perl
  /usr/local/lib/x86_64-linux-gnu/perl:
    bind: $SNAP/usr/local/lib/x86_64-linux-gnu/perl
  /usr/local/share/perl:
    bind: $SNAP/usr/local/share/perl
  /usr/lib/x86_64-linux-gnu/perl5:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl5
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/lib/x86_64-linux-gnu/perl-base:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl-base
  /usr/lib/x86_64-linux-gnu/perl:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl
  /usr/share/perl:
    bind: $SNAP/usr/share/perl
  /usr/local/lib/site_perl:
    bind: $SNAP/usr/local/lib/site_perl
  /usr/lib/postgresql/14:
    bind: $SNAP/usr/lib/postgresql/14
  /var/cache/postgresql:
    bind: $SNAP_COMMON/var/cache/postgresql
  $SNAP/usr/share/postgresql/14/extension/postgis.control:
    symlink: $SNAP/usr/share/postgresql/14/extension/postgis-3.control
  $SNAP/usr/share/postgresql/14/extension/address_standardizer.control:
    symlink: "$SNAP/usr/share/postgresql/14/extension/\
    address_standardizer-3.control"
  $SNAP/usr/share/postgresql/14/extension/address_standardizer_data_us.control:
    symlink: "$SNAP/usr/share/postgresql/14/extension/\
    address_standardizer_data_us-3.control"
  $SNAP/usr/share/postgresql/14/extension/postgis_raster.control:
    symlink: $SNAP/usr/share/postgresql/14/extension/postgis_raster-3.control
  $SNAP/usr/share/postgresql/14/extension/postgis_tiger_geocoder.control:
    symlink: "$SNAP/usr/share/postgresql/14/extension/\
    postgis_tiger_geocoder-3.control"
  $SNAP/usr/share/postgresql/14/extension/postgis_topology.control:
    symlink: $SNAP/usr/share/postgresql/14/extension/postgis_topology-3.control

# TODO: Add postgresql log path once configured
slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/patroni
        - $SNAP_COMMON/var/log/postgresql
        - $SNAP_COMMON/var/log/pgbackrest
        - $SNAP_COMMON/var/log/pgbouncer

apps:
  createdb:
    command: usr/bin/createdb
  createuser:
    command: usr/bin/createuser
  patroni:
    command: start-patroni.sh
    daemon: simple
    install-mode: disable
    restart-condition: always
    environment:
      TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/\
      $CRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/lapack"
    plugs:
      - network
      - network-bind
  patroni-raft-controller:
    command: usr/bin/patroni_raft_controller
  patronictl:
    command: usr/bin/patronictl
    plugs:
      - network
  patroni-aws:
    command: usr/bin/patroni_aws
  patroni-wale-restore:
    command: usr/bin/patroni_wale_restore
  pg-archivecleanup:
    command: usr/bin/pg_archivecleanup
  pg-buildext:
    command: usr/bin/pg_buildext
  pg-createcluster:
    command: usr/bin/pg_createcluster
  pg-dropcluster:
    command: usr/bin/pg_dropcluster
  pg-isready:
    command: usr/bin/pg_isready
  # pg-receivexlog:
  #   command: usr/bin/pg_receivexlog
  pg-restore:
    command: usr/bin/pg_restore
    plugs:
      - network
  pg-upgradecluster:
    command: usr/bin/pg_upgradecluster
  pg-backupcluster:
    command: usr/bin/pg_backupcluster
  pg-config:
    command: usr/bin/pg_config
  pg-dump:
    command: usr/bin/pg_dump
    plugs:
      - network
  pg-lsclusters:
    command: usr/bin/pg_lsclusters
  pg-recvlogical:
    command: usr/bin/pg_recvlogical
  pg-restorecluster:
    command: usr/bin/pg_restorecluster
  pg-virtualenv:
    command: usr/bin/pg_virtualenv
  pg-basebackup:
    command: usr/bin/pg_basebackup
  pg-conftool:
    command: usr/bin/pg_conftool
  pg-ctl:
    command: usr/lib/postgresql/14/bin/pg_ctl
  pg-ctlcluster:
    command: usr/bin/pg_ctlcluster
  pg-dumpall:
    command: usr/bin/pg_dumpall
    plugs:
      - network
  pg-receivewal:
    command: usr/bin/pg_receivewal
  pg-renamecluster:
    command: usr/bin/pg_renamecluster
  pg-updatedicts:
    command: usr/sbin/pg_updatedicts
  pgbackrest:
    command: usr/bin/pgbackrest
    plugs:
      - network
  pgbackrest-service:
    command: start-pgbackrest.sh
    daemon: simple
    plugs:
      - network
      - network-bind
  pgbench:
    command: usr/bin/pgbench
  pgbouncer:
    command: usr/sbin/pgbouncer
  pgbouncer-server:
    command: start-pgbouncer.sh
    plugs:
      - network
      - network-bind
  prometheus-postgres-exporter:
    command: start-exporter.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  prometheus-pgbouncer-exporter:
    command: start-pgb-exporter.sh
    plugs:
      - network
      - network-bind
  psql:
    command: usr/bin/psql
    plugs:
      - network
  syncobj-admin:
    command: usr/bin/syncobj_admin
    plugs:
      - network

parts:
  postgres-debs:
    plugin: nil
    stage-packages:
      - postgresql
      - util-linux
      - pgbouncer
      - pgbackrest
      - prometheus-postgres-exporter
      - golang-github-prometheus-community-pgbouncer-exporter
      - python3-pysyncobj
      - python3-boto3
      - patroni
      - locales-all
      # Landscape deps
      - postgresql-14-debversion
      - postgresql-plpython3-14
      - postgresql-contrib
      - postgresql-plperl-14
      - postgresql-14-similarity
      - postgresql-14-orafce
      - postgresql-14-hypopg
      - postgresql-14-hll
      - postgresql-14-ip4r
      - postgresql-pltcl-14
      - postgresql-14-prefix
      - postgresql-14-rdkit
      - postgresql-14-tds-fdw
      - postgresql-14-icu-ext
      - postgresql-14-postgis-3
      - postgresql-14-postgis-3-scripts

  wrapper:
    plugin: dump
    source: snap/local
