# yamllint disable rule:line-length
name: charmed-postgresql
base: core24
version: '16.10'
summary: PostgreSQL in a snap.
description: |
  PostgreSQL is a free and open-source relational database management
  system emphasizing extensibility and SQL compliance.  This package
  includes patroni for managing your PostgreSQL systems.

platforms:
  amd64:
  arm64:
grade: stable
confinement: strict

system-usernames:
  _daemon_: shared

plugs:
  shared-memory:
    private: true

package-repositories:
  - type: apt
    ppa: data-platform/postgresql-16-timescaledb-tsl
  - type: apt
    ppa: data-platform/pgbackrest
  - type: apt
    ppa: data-platform/pgbackrest-exporter
  - type: apt
    ppa: data-platform/postgresql-ldap-sync
  - type: apt
    ppa: data-platform/postgresql-login-hook

layout:
  /usr/bin/perl:
    symlink: $SNAP/usr/bin/perl
  /usr/lib/python3/dist-packages:
    bind: $SNAP/usr/lib/python3/dist-packages
  /etc/perl:
    bind: $SNAP/etc/perl
  /usr/local/lib/x86_64-linux-gnu/perl:
    bind: $SNAP/usr/local/lib/x86_64-linux-gnu/perl
  /usr/local/share/perl:
    bind: $SNAP/usr/local/share/perl
  /usr/lib/x86_64-linux-gnu/perl5:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl5
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/lib/x86_64-linux-gnu/perl-base:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl-base
  /usr/lib/x86_64-linux-gnu/perl:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl
  /usr/share/perl:
    bind: $SNAP/usr/share/perl
  /usr/local/lib/site_perl:
    bind: $SNAP/usr/local/lib/site_perl
  /usr/lib/postgresql/16:
    bind: $SNAP/usr/lib/postgresql/16
  /var/cache/postgresql:
    bind: $SNAP_COMMON/var/cache/postgresql
  $SNAP/usr/share/postgresql/16/extension/postgis.control:
    symlink: $SNAP/usr/share/postgresql/16/extension/postgis-3.control
  $SNAP/usr/share/postgresql/16/extension/address_standardizer.control:
    symlink: "$SNAP/usr/share/postgresql/16/extension/\
    address_standardizer-3.control"
  $SNAP/usr/share/postgresql/16/extension/address_standardizer_data_us.control:
    symlink: "$SNAP/usr/share/postgresql/16/extension/\
    address_standardizer_data_us-3.control"
  $SNAP/usr/share/postgresql/16/extension/postgis_raster.control:
    symlink: $SNAP/usr/share/postgresql/16/extension/postgis_raster-3.control
  $SNAP/usr/share/postgresql/16/extension/postgis_tiger_geocoder.control:
    symlink: "$SNAP/usr/share/postgresql/16/extension/\
    postgis_tiger_geocoder-3.control"
  $SNAP/usr/share/postgresql/16/extension/postgis_topology.control:
    symlink: $SNAP/usr/share/postgresql/16/extension/postgis_topology-3.control

slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/patroni
        - $SNAP_COMMON/var/log/postgresql
        - $SNAP_COMMON/var/log/pgbackrest
        - $SNAP_COMMON/var/log/pgbouncer

environment:
  # This variable will tell the LDAP binary where to get its configuration.
  # The default /etc/ldap/ldap.conf file is not readable for the snap user.
  # (https://manpages.debian.org/jessie/libldap-2.4-2/ldap.conf.5.en.html)
  LDAPCONF: $SNAP_DATA/etc/ldap/ldap.conf

apps:
  createdb:
    command: setpriv.sh $SNAP/usr/bin/createdb
  createuser:
    command: setpriv.sh $SNAP/usr/bin/createuser
  ldap-sync:
    command: start-ldap-synchronizer.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  patroni:
    command: start-patroni.sh
    daemon: simple
    install-mode: disable
    restart-condition: always
    environment:
      TCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.6
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/\
      $CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/\
      $CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack"
    plugs:
      - network
      - network-bind
  patroni-raft-controller:
    command: usr/bin/patroni_raft_controller
  patronictl:
    command: setpriv.sh $SNAP/usr/bin/patronictl
    plugs:
      - network
  patroni-aws:
    command: setpriv.sh $SNAP/usr/bin/patroni_aws
  patroni-wale-restore:
    command: setpriv.sh $SNAP/usr/bin/patroni_wale_restore
  pg-archivecleanup:
    command: setpriv.sh $SNAP/usr/bin/pg_archivecleanup
  pg-buildext:
    command: setpriv.sh $SNAP/usr/bin/pg_buildext
  pg-isready:
    command: setpriv.sh $SNAP/usr/bin/pg_isready
  pg-restore:
    command: setpriv.sh $SNAP/usr/bin/pg_restore
    plugs:
      - network
  pg-config:
    command: setpriv.sh $SNAP/usr/bin/pg_config
  pg-dump:
    command: setpriv.sh $SNAP/usr/bin/pg_dump
    plugs:
      - network
  pg-recvlogical:
    command: setpriv.sh $SNAP/usr/bin/pg_recvlogical
  pg-virtualenv:
    command: setpriv.sh $SNAP/usr/bin/pg_virtualenv
  pg-basebackup:
    command: setpriv.sh $SNAP/usr/bin/pg_basebackup
  pg-conftool:
    command: setpriv.sh $SNAP/usr/bin/pg_conftool
  pg-ctl:
    command: setpriv.sh $SNAP/usr/lib/postgresql/16/bin/pg_ctl
  pg-dumpall:
    command: setpriv.sh $SNAP/usr/bin/pg_dumpall
    plugs:
      - network
  pg-receivewal:
    command: setpriv.sh $SNAP/usr/bin/pg_receivewal
  pg-updatedicts:
    command: setpriv.sh $SNAP/usr/sbin/pg_updatedicts
  pgbackrest:
    command: setpriv.sh $SNAP/usr/bin/pgbackrest
    plugs:
      - network
  pgbackrest-service:
    command: start-pgbackrest.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  pgbackrest-exporter:
    command: start-pgbackrest-exporter.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  pgbench:
    command: usr/bin/pgbench
  pgbouncer:
    command: setpriv.sh $SNAP/usr/sbin/pgbouncer
  pgbouncer-server:
    command: start-pgbouncer.sh
    plugs:
      - network
      - network-bind
  prometheus-postgres-exporter:
    command: start-exporter.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  prometheus-pgbouncer-exporter:
    command: start-pgb-exporter.sh
    plugs:
      - network
      - network-bind
  psql:
    command: usr/bin/psql
    plugs:
      - network
  syncobj-admin:
    command: usr/bin/syncobj_admin
    plugs:
      - network

parts:
  postgres-debs:
    plugin: nil
    stage-packages:
      - postgresql=16+257build1.1
      - util-linux
      - pgbouncer=1.22.0-1build4
      - pgbackrest=2.53-1ubuntu0.24.04.1~ppa1
      - prometheus-postgres-exporter=0.15.0-1
      - golang-github-prometheus-community-pgbouncer-exporter=0.7.0-1
      - python3-pysyncobj=0.3.12-1
      - patroni=3.2.2-2
      - prometheus-pgbackrest-exporter=0.17.0+ds1-0ubuntu0.24.04.1~ppa1
      - python3-postgresql-ldap-sync=0.3.2-0ubuntu1
      - locales-all
      - libldap-common
      # Landscape deps
      - postgresql-16-timescaledb-tsl=2.18.2-0ubuntu0.24.04.2~ppa1
      - postgresql-16-debversion=1.1.2-3build2
      - postgresql-plpython3-16=16.10-0ubuntu0.24.04.1
      - postgresql-contrib=16+257build1.1
      - postgresql-plperl-16
      - postgresql-16-similarity
      - postgresql-16-orafce
      - postgresql-16-hypopg
      - postgresql-16-hll
      - postgresql-16-ip4r
      - postgresql-pltcl-16
      - postgresql-16-prefix
      - postgresql-16-rdkit
      - postgresql-16-tds-fdw
      - postgresql-16-icu-ext
      - postgresql-16-postgis-3
      - postgresql-16-postgis-3-scripts
      - postgresql-16-pgvector
      - postgresql-16-pgaudit
      - postgresql-16-set-user
      - postgresql-16-login-hook
      - postgresql-16-repack
    organize:
      usr/share/doc/postgresql/copyright: licenses/COPYRIGHT-postgresql
      usr/share/doc/util-linux/copyright: licenses/COPYRIGHT-util-linux
      usr/share/doc/pgbouncer/copyright: licenses/COPYRIGHT-pgbouncer
      usr/share/doc/pgbackrest/copyright: licenses/COPYRIGHT-pgbackrest
      usr/share/doc/prometheus-postgres-exporter/copyright: licenses/COPYRIGHT-prometheus-postgres-exporter
      usr/share/doc/golang-github-prometheus-community-pgbouncer-exporter/copyright: licenses/COPYRIGHT-golang-github-prometheus-community-pgbouncer-exporter
      usr/share/doc/python3-postgresql-ldap-sync/copyright: licenses/COPYRIGHT-python3-postgresql-ldap-sync
      usr/share/doc/python3-pysyncobj/copyright: licenses/COPYRIGHT-python3-pysyncobj
      usr/share/doc/patroni/copyright: licenses/COPYRIGHT-patroni
      usr/share/doc/locales-all/copyright: licenses/COPYRIGHT-locales-all
      usr/share/doc/libldap-common/copyright: licenses/COPYRIGHT-libldap-common
      usr/share/doc/postgresql-16-debversion/copyright: licenses/COPYRIGHT-postgresql-16-debversion
      usr/share/doc/postgresql-plpython3-16/copyright: licenses/COPYRIGHT-postgresql-plpython3-16
      usr/share/doc/postgresql-contrib/copyright: licenses/COPYRIGHT-postgresql-contrib
      usr/share/doc/postgresql-plperl-16/copyright: licenses/COPYRIGHT-plperl
      usr/share/doc/postgresql-similarity-16/copyright: licenses/COPYRIGHT-similarity
      usr/share/doc/postgresql-orafce-16/copyright: licenses/COPYRIGHT-orafce
      usr/share/doc/postgresql-16-hypopg/copyright: licenses/COPYRIGHT-hypopg
      usr/share/doc/postgresql-16-hll/copyright: licenses/COPYRIGHT-hll
      usr/share/doc/postgresql-16-ip4r/copyright: licenses/COPYRIGHT-ip4r
      usr/share/doc/postgresql-pltcl-16/copyright: licenses/COPYRIGHT-pltcl
      usr/share/doc/postgresql-16-prefix/copyright: licenses/COPYRIGHT-prefix
      usr/share/doc/postgresql-16-rdkit/copyright: licenses/COPYRIGHT-rdkit
      usr/share/doc/postgresql-16-tds-fdw/copyright: licenses/COPYRIGHT-tds-fdw
      usr/share/doc/postgresql-16-icu-ext/copyright: licenses/COPYRIGHT-icu-ext
      usr/share/doc/postgresql-16-postgis-3/copyright: licenses/COPYRIGHT-postgis
      usr/share/doc/postgresql-16-pgvector/copyright: licenses/COPYRIGHT-pgvector
      usr/share/doc/postgresql-16-pgaudit/copyright: licenses/COPYRIGHT-pgaudit
      usr/share/doc/postgresql-16-timescaledb-tsl/copyright: licenses/COPYRIGHT-timescaledb
      usr/share/doc/prometheus-pgbackrest-exporter/copyright: licenses/COPYRIGHT-pgbackrest-exporter
      usr/share/doc/postgresql-16-set-user/copyright: licenses/COPYRIGHT-set-user
      usr/share/doc/postgresql-16-login-hook/copyright: licences/COPYRIGHT-login-hook
      usr/share/doc/postgresql-16-repack/copyright: licences/COPYRIGHT-repack
  snap-license:
    plugin: dump
    source: .
    source-type: local
    stage:
      - licenses/LICENSE-snap
    organize:
      LICENSE: licenses/LICENSE-snap
  wrapper:
    plugin: dump
    source: snap/local
