# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Snap Store

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '*/edge'
    paths:
      - snap/**
  workflow_dispatch:

jobs:
  ci-tests:
    name: Tests
    uses: ./.github/workflows/ci.yaml
    permissions: {}

  release:
    name: Release snap
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_snap.yaml@v42.0.1
    with:
      channel: ${{ github.ref_name }}
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN }}
    permissions:
      contents: write  # Needed to create GitHub release
