on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Snap
    uses: ./.github/workflows/build.yaml
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: postgres-snap
      - name: Install tox
        run: python3 -m pip install tox
      - name: Smoke Tests
        run: tox -e smoke
