#!/bin/bash

mkdir -p $SNAP_DATA/etc/postgresql
mkdir -p $SNAP_DATA/pgsql/
mkdir -p $SNAP_DATA/pgsql/data

mkdir -p $SNAP_COMMON/postgresql.failed
mkdir -p $SNAP_COMMON/data/db

mkdir -p $SNAP_COMMON/var/lib/postgresql
mkdir -p $SNAP_COMMON/var/log/postgresql

chown -R 584788:root $SNAP_COMMON/*
chown -R 584788:root $SNAP_DATA/*

export LOCPATH="${SNAP}"/usr/lib/locale
export PGDATA=$SNAP_DATA/pgsql/data

## NOT RUNNING
mkdir /home/snap_daemon
chown -R 584788:root /home/snap_daemon
usermod -d /home/snap_daemon snap_daemon

echo "Initializing PostgreSQL data directory..."
"${SNAP}/usr/bin/setpriv" --clear-groups --reuid snap_daemon --regid snap_daemon -- "${SNAP}/usr/lib/postgresql/14/bin/pg_ctl" initdb -D "${PGDATA}"

