#!/bin/bash

VAR_LIB_PGBACKREST=$SNAP_COMMON/var/lib/pgbackrest

mkdir -p $SNAP_DATA/etc/patroni
mkdir -p $SNAP_DATA/etc/postgresql
mkdir -p $SNAP_DATA/etc/pgbackrest

mkdir -p $VAR_LIB_PGBACKREST
mkdir -p $SNAP_COMMON/postgresql.failed
mkdir -p $SNAP_COMMON/data/db

mkdir -p $SNAP_COMMON/var/lib/postgresql
mkdir -p $SNAP_COMMON/var/log/patroni
mkdir -p $SNAP_COMMON/var/log/pgbackrest

cp $SNAP/config/patroni.yaml $SNAP_DATA/etc/patroni
cp $SNAP/etc/pgbackrest.conf $SNAP_DATA/etc/pgbackrest

sed -i "s:/var/lib/pgbackrest:$VAR_LIB_PGBACKREST:g" $SNAP_DATA/etc/pgbackrest/pgbackrest.conf
echo "pg1-path=$SNAP_COMMON/var/lib/postgresql" >> $SNAP_DATA/etc/pgbackrest/pgbackrest.conf
echo "pg1-user=snap_daemon" >> $SNAP_DATA/etc/pgbackrest/pgbackrest.conf

chown -R 584788:root $SNAP_COMMON/*
chown -R 584788:root $SNAP_DATA/*
